version: '3.9'

services:
  partner_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 6600:5432
    networks:
      - partner_net
    deploy:  
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  partner:
    build: .
    environment:
      GUNICORN: false
    volumes:
      - .:/usr/app
    ports:
      - 6650:80
    networks:
      - partner_net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
    depends_on:
      partner_db:
        condition: service_started

networks:
  partner_net:
    driver: bridge
    name: partner_net