from marshmallow import Schema, fields

class PartnerDeserializeSchema(Schema):
    user = fields.UUID()
    name = fields.String()
    last_name = fields.String()
    age = fields.Integer()
    profession = fields.String()
    license = fields.String(required=False)
    identification_type = fields.String()
    identification = fields.String()
    country_birth = fields.String()
    city_birth =  fields.String()
    country_residence =  fields.String()
    city_residence =  fields.String()
    sports = fields.List(fields.String(), required=True)
    companies = fields.List(fields.String(), required=True)
    type_services = fields.List(fields.String(), required=True)

class PartnerSerializeSchema(Schema):
    name = fields.String()
    last_name = fields.String()
    age = fields.Integer()
    profession = fields.String()
    license = fields.String()
    license = fields.String()
    identification_type = fields.String()
    identification = fields.String()
    country_birth = fields.String()
    city_birth =  fields.String()
    country_residence =  fields.String()
    city_residence =  fields.String()
    sports = fields.List(fields.String())
    companies = fields.List(fields.String())
    type_services = fields.List(fields.String())
    updated_at = fields.DateTime(format='%Y-%m-%dT%H:%M:%S%z')
    created_at = fields.DateTime(format='%Y-%m-%dT%H:%M:%S%z')